[project]
name = "gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain==0.2.16",
    "langchain-community==0.2.16",
    "langchain-core==0.2.38",
    "langchain-google-genai==1.0.6",
    "langchain-text-splitters==0.2.2",
    "pypdf2>=3.0.1",
    "sentence-transformers>=5.2.3",
    "streamlit>=1.54.0",
]
